# Add project specific ProGuard rules here.
# You can control the set of applied configuration files using the
# proguardFiles setting in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}

# Uncomment this to preserve the line number information for
# debugging stack traces.
#-keepattributes SourceFile,LineNumberTable

# If you keep the line number information, uncomment this to
# hide the original source file name.
#-renamesourcefileattribute SourceFile

# R8 generated: suppress warnings for classes used by JCIFS (SMB) / GSSAPI
# that are not present on Android.
-dontwarn javax.el.BeanELResolver
-dontwarn javax.el.ELContext
-dontwarn javax.el.ELResolver
-dontwarn javax.el.ExpressionFactory
-dontwarn javax.el.FunctionMapper
-dontwarn javax.el.ValueExpression
-dontwarn javax.el.VariableMapper
-dontwarn org.ietf.jgss.GSSContext
-dontwarn org.ietf.jgss.GSSCredential
-dontwarn org.ietf.jgss.GSSException
-dontwarn org.ietf.jgss.GSSManager
-dontwarn org.ietf.jgss.GSSName
-dontwarn org.ietf.jgss.Oid

# Apache POI — keep Escher/DDF record fields accessed via reflection.
# DefaultEscherRecordFactory uses Class.getField("RECORD_ID") in its static initializer.
# Without this, R8 strips RECORD_ID causing java.lang.NoSuchFieldException at runtime.
-keepclassmembers class org.apache.poi.ddf.** {
    public static final short RECORD_ID;
}

# Apache POI — java.awt and javax.xml classes not present on Android
-dontwarn java.awt.Color
-dontwarn java.awt.Dimension
-dontwarn java.awt.Rectangle
-dontwarn java.awt.geom.Rectangle2D$Double
-dontwarn java.awt.geom.Rectangle2D
-dontwarn javax.xml.bind.DatatypeConverter
-dontwarn javax.xml.stream.XMLEventFactory
-dontwarn javax.xml.stream.XMLStreamReader
-dontwarn javax.xml.stream.events.Namespace

# xmlbeans optional service providers (XPath/XQuery, not used by UFM)
-dontwarn org.apache.xmlbeans.impl.store.PathDelegate$SelectPathInterface
-dontwarn org.apache.xmlbeans.impl.store.QueryDelegate$QueryInterface

# JCIFS-NG and its dependencies (required for Release builds)
# Keep only packages actually used — jcifs.smb1.* is intentionally excluded
# so R8 strips SMB1 classes from the release APK.
-keep class jcifs.CIFSContext { *; }
-keep class jcifs.config.** { *; }
-keep class jcifs.context.** { *; }
-keep class jcifs.smb.** { *; }
-keep class eu.agno3.jcifs.** { *; }
-keep class org.bouncycastle.** { *; }

# ── smbj (com.hierynomus:smbj) ──────────────────────────────────────────────
# smbj uses reflection/ServiceLoader to load its JceSecurityProvider and
# uses enum constants + sealed class hierarchies for SMB2/3 packet encoding.
# R8 strips/renames these classes in release builds, causing:
#   - Silent crypto negotiation failures → repeated retries/timeouts
#   - SPNEGO/NTLM auth fallback loops
#   - Massive slowdown on ALL SMB operations (list, open, thumbnails, transfer)
# This is the root cause of "debug fast, release very slow" SMB behavior.
-keep class com.hierynomus.smbj.** { *; }
-keep class com.hierynomus.mssmb2.** { *; }
-keep class com.hierynomus.msfscc.** { *; }
-keep class com.hierynomus.protocol.** { *; }
-keep class com.hierynomus.security.** { *; }
-keep class com.hierynomus.asn1.** { *; }
-keep class com.hierynomus.ntlm.** { *; }
-keep class com.hierynomus.spnego.** { *; }
-keep class com.hierynomus.msdtyp.** { *; }
-keep class com.hierynomus.mserref.** { *; }
-dontwarn com.hierynomus.**

# MBassador event bus — transitive dependency of smbj.
# Uses reflection to instantiate event subscription handlers via constructors.
# R8 obfuscates these classes, causing "provider handler invocation did not
# specify the necessary constructor" errors at runtime.
-keep class net.engio.mbassy.** { *; }

# Suppress warnings for optional/legacy components not used or present on Android
-dontwarn org.bouncycastle.**
-dontwarn jcifs.http.**

# Missing R8 rules for security/auth classes (generated by build)
-dontwarn javax.security.auth.callback.NameCallback
-dontwarn javax.security.auth.kerberos.KerberosKey
-dontwarn javax.security.auth.kerberos.KerberosPrincipal
-dontwarn javax.security.auth.kerberos.KerberosTicket
-dontwarn javax.security.auth.login.AppConfigurationEntry$LoginModuleControlFlag
-dontwarn javax.security.auth.login.AppConfigurationEntry
-dontwarn javax.security.auth.login.Configuration
-dontwarn javax.security.auth.login.LoginContext
-dontwarn org.ietf.jgss.MessageProp

# Keep Room-generated implementations used by WorkManager (avoid R8 stripping them)
-keep class * extends androidx.room.RoomDatabase { *; }
# WorkManager internal DB implementation
-keep class androidx.work.impl.WorkDatabase_Impl { *; }
-keep class androidx.work.impl.WorkDatabase$* { *; }

# Keep generated Room/DAO implementations (broad rule to be safe for release builds)
-keep class **_Impl { *; }

# Missing R8 rules for security/auth and tink-crypto (generated by build)
-dontwarn com.google.crypto.tink.subtle.Ed25519Sign$KeyPair
-dontwarn com.google.crypto.tink.subtle.Ed25519Sign
-dontwarn com.google.crypto.tink.subtle.Ed25519Verify
-dontwarn com.google.crypto.tink.subtle.X25519
-dontwarn com.google.crypto.tink.subtle.XChaCha20Poly1305
-dontwarn javax.management.MBeanException
-dontwarn javax.management.ReflectionException
-dontwarn javax.security.auth.login.CredentialException
-dontwarn javax.security.auth.login.FailedLoginException

# Missing R8 rules for Netty, Logging, and Java internal APIs (generated by build)
-dontwarn io.netty.internal.tcnative.AsyncSSLPrivateKeyMethod
-dontwarn io.netty.internal.tcnative.AsyncTask
-dontwarn io.netty.internal.tcnative.Buffer
-dontwarn io.netty.internal.tcnative.CertificateCallback
-dontwarn io.netty.internal.tcnative.CertificateCompressionAlgo
-dontwarn io.netty.internal.tcnative.CertificateVerifier
-dontwarn io.netty.internal.tcnative.Library
-dontwarn io.netty.internal.tcnative.SSL
-dontwarn io.netty.internal.tcnative.SSLContext
-dontwarn io.netty.internal.tcnative.SSLPrivateKeyMethod
-dontwarn io.netty.internal.tcnative.SSLSessionCache
-dontwarn io.netty.internal.tcnative.SessionTicketKey
-dontwarn io.netty.internal.tcnative.SniHostNameMatcher
-dontwarn java.lang.management.ManagementFactory
-dontwarn java.lang.management.RuntimeMXBean
-dontwarn jdk.jfr.Category
-dontwarn jdk.jfr.Description
-dontwarn jdk.jfr.Enabled
-dontwarn jdk.jfr.Event
-dontwarn jdk.jfr.FlightRecorder
-dontwarn jdk.jfr.Label
-dontwarn jdk.jfr.Name
-dontwarn org.apache.log4j.Level
-dontwarn org.apache.log4j.Logger
-dontwarn org.apache.log4j.Priority
-dontwarn org.apache.logging.log4j.Level
-dontwarn org.apache.logging.log4j.LogManager
-dontwarn org.apache.logging.log4j.Logger
-dontwarn org.apache.logging.log4j.message.MessageFactory
-dontwarn org.apache.logging.log4j.spi.ExtendedLogger
-dontwarn org.apache.logging.log4j.spi.ExtendedLoggerWrapper
-dontwarn reactor.blockhound.integration.BlockHoundIntegration

# Apache SSHD, MINA, and FTPServer use ServiceLoader and reflection which R8 breaks in release.
# IMPORTANT: The broad -keep for org.apache.ftpserver.** is also required to preserve the
# thread-safety patch at app/src/main/java/org/apache/ftpserver/listener/nio/FtpResponseEncoder.java.
# That class shadows the broken library version and MUST retain its exact package name at runtime.
# See: java.nio.charset.CoderMalfunctionError fix — shared static CharsetEncoder → ThreadLocal.
-keep class org.apache.sshd.** { *; }
-keep class org.apache.mina.** { *; }
-keep class org.apache.ftpserver.** { *; }
-keep class net.i2p.crypto.eddsa.** { *; }

# Suppress missing classes generated by R8
-dontwarn java.rmi.RemoteException
-dontwarn java.rmi.ServerException
-dontwarn javax.security.sasl.AuthenticationException
-dontwarn javax.security.sasl.SaslException
-dontwarn org.apache.tomcat.jni.Error
-dontwarn org.apache.tomcat.jni.File
-dontwarn org.apache.tomcat.jni.Library
-dontwarn org.apache.tomcat.jni.Local
-dontwarn org.apache.tomcat.jni.Pool
-dontwarn org.apache.tomcat.jni.Socket
-dontwarn org.springframework.beans.factory.FactoryBean
-dontwarn org.springframework.beans.factory.config.BeanDefinition
-dontwarn org.springframework.beans.factory.config.BeanDefinitionHolder
-dontwarn org.springframework.beans.factory.support.AbstractBeanDefinition
-dontwarn org.springframework.beans.factory.support.BeanDefinitionBuilder
-dontwarn org.springframework.beans.factory.support.BeanDefinitionRegistry
-dontwarn org.springframework.beans.factory.support.ManagedMap
-dontwarn org.springframework.beans.factory.xml.AbstractSingleBeanDefinitionParser
-dontwarn org.springframework.beans.factory.xml.BeanDefinitionParser
-dontwarn org.springframework.beans.factory.xml.BeanDefinitionParserDelegate
-dontwarn org.springframework.beans.factory.xml.NamespaceHandlerSupport
-dontwarn org.springframework.beans.factory.xml.ParserContext
-dontwarn org.springframework.beans.factory.xml.XmlReaderContext
-dontwarn org.springframework.context.support.FileSystemXmlApplicationContext
-dontwarn org.springframework.util.StringUtils
-dontwarn org.springframework.util.xml.DomUtils
-dontwarn sun.security.x509.X509Key

# Ktor Web Server & Netty (Remote Manager) use reflection, ServiceLoader and coroutine metadata
-keep class io.ktor.** { *; }
-keep class io.netty.** { *; }
-keep class org.slf4j.** { *; }

# Additional suppressions for Netty optional missing classes
-dontwarn com.aayushatharva.brotli4j.Brotli4jLoader
-dontwarn com.aayushatharva.brotli4j.decoder.DecoderJNI$Status
-dontwarn com.aayushatharva.brotli4j.decoder.DecoderJNI$Wrapper
-dontwarn com.aayushatharva.brotli4j.encoder.BrotliEncoderChannel
-dontwarn com.aayushatharva.brotli4j.encoder.Encoder$Mode
-dontwarn com.aayushatharva.brotli4j.encoder.Encoder$Parameters
-dontwarn com.github.luben.zstd.Zstd
-dontwarn com.github.luben.zstd.ZstdInputStreamNoFinalizer
-dontwarn com.github.luben.zstd.util.Native
-dontwarn com.jcraft.jzlib.Deflater
-dontwarn com.jcraft.jzlib.Inflater
-dontwarn com.jcraft.jzlib.JZlib$WrapperType
-dontwarn com.jcraft.jzlib.JZlib
-dontwarn com.ning.compress.BufferRecycler
-dontwarn com.ning.compress.lzf.ChunkDecoder
-dontwarn com.ning.compress.lzf.ChunkEncoder
-dontwarn com.ning.compress.lzf.LZFChunk
-dontwarn com.ning.compress.lzf.LZFEncoder
-dontwarn com.ning.compress.lzf.util.ChunkDecoderFactory
-dontwarn com.ning.compress.lzf.util.ChunkEncoderFactory
-dontwarn com.oracle.svm.core.annotate.Alias
-dontwarn com.oracle.svm.core.annotate.InjectAccessors
-dontwarn com.oracle.svm.core.annotate.RecomputeFieldValue$Kind
-dontwarn com.oracle.svm.core.annotate.RecomputeFieldValue
-dontwarn com.oracle.svm.core.annotate.TargetClass
-dontwarn com.sun.nio.file.SensitivityWatchEventModifier
-dontwarn io.netty.internal.tcnative.ResultCallback
-dontwarn io.netty.internal.tcnative.SSLSession
-dontwarn io.netty.pkitesting.CertificateBuilder$Algorithm
-dontwarn io.netty.pkitesting.CertificateBuilder
-dontwarn io.netty.pkitesting.X509Bundle
-dontwarn jdk.jfr.DataAmount
-dontwarn jdk.jfr.MemoryAddress
-dontwarn lzma.sdk.ICodeProgress
-dontwarn lzma.sdk.lzma.Encoder
-dontwarn net.jpountz.lz4.LZ4Compressor
-dontwarn net.jpountz.lz4.LZ4Exception
-dontwarn net.jpountz.lz4.LZ4Factory
-dontwarn net.jpountz.lz4.LZ4FastDecompressor
-dontwarn net.jpountz.xxhash.XXHash32
-dontwarn net.jpountz.xxhash.XXHashFactory
-dontwarn org.osgi.annotation.bundle.Export
-dontwarn reactor.blockhound.BlockHound$Builder

# ── Amazon Appstore SDK (IAP 3.0.8) ──────────────────────────────────────────
# Required by Amazon: the PurchasingListener callbacks and ResponseReceiver are
# invoked via reflection and broadcast intents from the Appstore process.
# Without these rules R8 will strip or rename the IAP classes and purchases break.
-dontwarn com.amazon.**
-keep class com.amazon.device.iap.** { *; }
-keep class com.amazon.device.drm.** { *; }
-keepattributes *Annotation*

# ── PDFBox-Android (PDF Conversion) ──────────────────────────────────────────
-keep class com.tom_roush.pdfbox.** { *; }
-dontwarn javax.xml.stream.**
-dontwarn javax.xml.namespace.**

# ── EMC ECS NFS Client (Netty 3.x: org.jboss.netty) ────────────────────────────
# NfsShareClient + NFS RPC runtime classes accessed via reflection
-keep class com.emc.ecs.nfsclient.** { *; }

# Netty 3 (org.jboss.netty) — used by nfs-client for NIO transport.
# Heavily uses reflection for ChannelPipeline, ChannelFactory, Selector, etc.
-keep class org.jboss.netty.** { *; }

# Suppress warnings for optional Netty 3 components not available on Android
-dontwarn org.jboss.netty.**
-dontwarn com.sun.jna.**

# Missing R8 rules (generated by build)
-dontwarn com.gemalto.jp2.JP2Decoder
-dontwarn com.gemalto.jp2.JP2Encoder

# Keep strings.xml and static fields of R$string class from obfuscation or shrinking
-keepclassmembers class **.R$string {
    public static <fields>;
}

# ── Native libnfs JNI Bridge ────────────────────────────────────────────────
# Preserve the LibNfsBridge class and its native methods to prevent rename,
# which would cause UnsatisfiedLinkError at runtime since C JNI symbols match
# the fully qualified package/class name.
-keep class za.kilowatch.ultimatefilemanager.network.LibNfsBridge {
    *;
}

# ── R8 DontWarn Rules (third-party optional dependencies) ─────────────────
-dontwarn com.google.protobuf.ExtensionRegistry
-dontwarn com.google.protobuf.ExtensionRegistryLite
-dontwarn com.google.protobuf.MessageLite$Builder
-dontwarn com.google.protobuf.MessageLite
-dontwarn com.google.protobuf.MessageLiteOrBuilder
-dontwarn com.google.protobuf.Parser
-dontwarn com.google.protobuf.nano.CodedOutputByteBufferNano
-dontwarn com.google.protobuf.nano.MessageNano
-dontwarn io.netty.internal.tcnative.SSLCredential
-dontwarn javax.naming.ldap.LdapName
-dontwarn javax.naming.ldap.Rdn
-dontwarn org.jboss.marshalling.ByteInput
-dontwarn org.jboss.marshalling.ByteOutput
-dontwarn org.jboss.marshalling.Marshaller
-dontwarn org.jboss.marshalling.MarshallerFactory
-dontwarn org.jboss.marshalling.MarshallingConfiguration
-dontwarn org.jboss.marshalling.Unmarshaller