package za.kilowatch.ultimatefilemanager.ui.policy

import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.widget.ImageView
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.TextView
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import org.json.JSONArray
import za.kilowatch.ultimatefilemanager.R
import za.kilowatch.ultimatefilemanager.settings.FontSizeHelper
import za.kilowatch.ultimatefilemanager.settings.LocaleHelper
import za.kilowatch.ultimatefilemanager.settings.ThemeHelper

/**
 * Open Source Licenses screen.
 *
 * Reads the licenses.json file generated by the cashapp/licensee Gradle plugin
 * (placed in res/raw/ during build) and displays each library's name, version,
 * and SPDX license identifier in a scrollable list.
 *
 * Falls back to a curated static list if the generated JSON is not yet present
 * (e.g. first-run after a clean in development).
 */
class LicensesActivity : AppCompatActivity() {

    private var isTvDevice = false

    companion object {
        fun start(context: Context) =
            context.startActivity(Intent(context, LicensesActivity::class.java))
    }

    override fun attachBaseContext(newBase: Context) {
        super.attachBaseContext(LocaleHelper.wrap(newBase))
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        ThemeHelper.applyTheme(this)
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()

        val isTv = za.kilowatch.ultimatefilemanager.util.DeviceUtils.isTvDevice(this)
        isTvDevice = isTv

        // ── Root layout ──────────────────────────────────────────────────────
        val root = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            setBackgroundResource(R.drawable.bg_mobile_gradient)
            id = R.id.main
        }

        // ── Header bar ───────────────────────────────────────────────────────
        val header = LinearLayout(this).apply {
            orientation = LinearLayout.HORIZONTAL
            gravity = android.view.Gravity.CENTER_VERTICAL
            val pad = (16 * resources.displayMetrics.density).toInt()
            setPadding(pad, pad, pad, pad)
            setBackgroundColor(getColor(if (isTv) R.color.tv_glass_white_10 else R.color.mobile_glass_header))
            minimumHeight = (if (isTv) 80 else 72).let { (it * resources.displayMetrics.density).toInt() }
        }

        val btnBack = ImageView(this).apply {
            setImageResource(R.drawable.ic_arrow_back)
            contentDescription = getString(R.string.cd_back)
            val sizeDp = if (isTv) 52 else 44
            val size = (sizeDp * resources.displayMetrics.density).toInt()
            layoutParams = LinearLayout.LayoutParams(size, size)
            isFocusable = true
            if (isTv) {
                // Set a rounded background drawable so the yellow tint is visible on focus
                val bg = android.graphics.drawable.GradientDrawable().apply {
                    shape = android.graphics.drawable.GradientDrawable.OVAL
                    setColor(android.graphics.Color.TRANSPARENT)
                }
                background = bg
                imageTintList = android.content.res.ColorStateList.valueOf(getColor(R.color.tv_text_primary))
                setOnFocusChangeListener { _, hasFocus ->
                    bg.setColor(
                        if (hasFocus) getColor(R.color.tv_button_focused_yellow)
                        else android.graphics.Color.TRANSPARENT
                    )
                    imageTintList = android.content.res.ColorStateList.valueOf(
                        if (hasFocus) getColor(R.color.tv_button_focused_yellow_text)
                        else getColor(R.color.tv_text_primary)
                    )
                }
            } else {
                imageTintList = android.content.res.ColorStateList.valueOf(getColor(R.color.mobile_icon_tint))
            }
            setOnClickListener { finish() }
        }

        val titleText = TextView(this).apply {
            text = getString(R.string.policy_licenses_button)
            setTextColor(getColor(if (isTv) R.color.tv_text_primary else R.color.mobile_text_primary))
            textSize = if (isTv) 22f else 20f
            typeface = android.graphics.Typeface.DEFAULT_BOLD
            val margin = (16 * resources.displayMetrics.density).toInt()
            layoutParams = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.WRAP_CONTENT,
                LinearLayout.LayoutParams.WRAP_CONTENT
            ).also { it.marginStart = margin }
        }

        header.addView(btnBack)
        header.addView(titleText)

        // ── Scroll area ───────────────────────────────────────────────────────
        val scroll = ScrollView(this).apply {
            layoutParams = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT,
                LinearLayout.LayoutParams.MATCH_PARENT
            )
        }

        val content = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            val pad = (16 * resources.displayMetrics.density).toInt()
            setPadding(pad, pad, pad, (pad * 3))
        }

        // ── Load license data ─────────────────────────────────────────────────
        val libraries = loadLibraries()

        if (libraries.isEmpty()) {
            content.addView(makeBodyText(
                "No license information available.\n\n" +
                getString(R.string.please_build_the_project_once_to_generate_the_license_report),
                isBody = true
            ))
        } else {
            libraries.forEach { lib ->
                content.addView(makeLibraryCard(lib))
            }
        }

        scroll.addView(content)
        root.addView(header)
        root.addView(scroll)

        setContentView(root)

        ViewCompat.setOnApplyWindowInsetsListener(root) { v, insets ->
            val bars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            v.setPadding(bars.left, bars.top, bars.right, bars.bottom)
            insets
        }
    }

    // ── Data loading ──────────────────────────────────────────────────────────

    private data class LibInfo(val name: String, val version: String, val license: String, val url: String)

    private fun loadLibraries(): List<LibInfo> {
        return try {
            val rawId = resources.getIdentifier("licenses", "raw", packageName)
            if (rawId == 0) return staticFallback()
            val json = resources.openRawResource(rawId).bufferedReader().readText()
            val arr = JSONArray(json)
            val list = (0 until arr.length()).map { i ->
                val obj = arr.getJSONObject(i)
                val name = obj.optString("name").ifBlank { obj.optString("groupId") + ":" + obj.optString("artifactId") }
                val version = obj.optString("version", "")
                val spdx = obj.optJSONArray("spdxLicenses")?.let { spdxArr ->
                    (0 until spdxArr.length()).joinToString(", ") { j ->
                        spdxArr.getJSONObject(j).optString("identifier", "")
                    }
                } ?: obj.optJSONArray("unknownLicenses")?.let { ul ->
                    (0 until ul.length()).joinToString(", ") { j ->
                        ul.getJSONObject(j).optString("name", "Unknown")
                    }
                } ?: getString(R.string.see_project_page)
                val url = obj.optString("scm", "").ifBlank {
                    obj.optJSONArray("spdxLicenses")?.optJSONObject(0)?.optString("url", "") ?: ""
                }
                LibInfo(name, version, spdx, url)
            }.toMutableList()

            if (list.none { it.name.contains("rclone", ignoreCase = true) }) {
                list.add(LibInfo(getString(R.string.add_online_storage_rclone), "1.75.0", "MIT", "https://github.com/rclone/rclone"))
            }
            if (list.none { it.name.contains("ffmpeg", ignoreCase = true) }) {
                list.add(LibInfo(getString(R.string.ffmpeg_lgpl_build), "8.1.2", "LGPL-2.1", "https://ffmpeg.org"))
            }
            if (list.none { it.name.contains("shizuku", ignoreCase = true) || it.name.contains("shevery", ignoreCase = true) }) {
                list.add(LibInfo("Shizuku & Shevery API (dev.rikka.shizuku:api)", "13.1.5", "Apache-2.0", "https://github.com/HmnDev-Tech/shevery"))
            }

            list.sortedBy { it.name.lowercase() }
        } catch (e: Exception) {
            staticFallback()
        }
    }

    private fun staticFallback() = listOf(
        LibInfo(getString(R.string.jcifsng_euagno3), "2.1.10", "LGPL-2.1", "https://github.com/AgNO3/jcifs-ng"),
        LibInfo(getString(R.string.smbj_hierynomus), "0.13.0", "Apache-2.0", "https://github.com/hierynomus/smbj"),
        LibInfo(getString(R.string.apache_commons_net), "3.10.0", "Apache-2.0", "https://commons.apache.org/proper/commons-net/"),
        LibInfo(getString(R.string.apache_commons_compress), "1.26.1", "Apache-2.0", "https://commons.apache.org/proper/commons-compress/"),
        LibInfo(getString(R.string.zip4j_netlingalazip4j), "2.11.5", "Apache-2.0", "https://github.com/svenkubiak/zip4j"),
        LibInfo(getString(R.string.xz_for_java_orgtukaanixz), "1.9", getString(R.string.public_domain), "https://tukaani.org/xz/java.html"),
        LibInfo(getString(R.string.apache_poi), "3.17", "Apache-2.0", "https://poi.apache.org/"),
        LibInfo(getString(R.string.nanohttpd), "2.3.1", "BSD-3-Clause", "https://github.com/NanoHttpd/nanohttpd"),
        LibInfo(getString(R.string.google_firebase_analytics), "", "Apache-2.0", "https://firebase.google.com/"),
        LibInfo(getString(R.string.google_billing_library), "", "Apache-2.0", "https://developer.android.com/google/play/billing"),
        LibInfo(getString(R.string.google_play_review_library), "2.0.2", "Apache-2.0", "https://developer.android.com/guide/playcore/in-app-review"),
        LibInfo(getString(R.string.androidx_libraries), "", "Apache-2.0", "https://developer.android.com/jetpack"),
        LibInfo(getString(R.string.viewpager2), "1.1.0", "Apache-2.0", "https://developer.android.com/jetpack/androidx/releases/viewpager2"),
        LibInfo(getString(R.string.libadbandroid_comgithubmuntashirakon), "3.1.1", "Apache-2.0", "https://github.com/MuntashirAkon/libadb-android"),
        LibInfo(getString(R.string.apache_sshd_core), "2.17.1", "Apache-2.0", "https://mina.apache.org/sshd-project/"),
        LibInfo(getString(R.string.eddsa_java), "0.3.0", "CC0-1.0", "https://github.com/str4d/ed25519-java"),
        LibInfo(getString(R.string.slf4j_android), "2.0.17-0", "MIT", "https://github.com/mizool/slf4j-android"),
        LibInfo(getString(R.string.bouncycastle_orgbouncycastle), "1.83", getString(R.string.bouncy_castle_license_mitstyle), "https://www.bouncycastle.org/java.html"),
        LibInfo(getString(R.string.coil_iocoilkt), "3.4.0", "Apache-2.0", "https://github.com/coil-kt/coil"),
        LibInfo(getString(R.string.apng4android_comgithubpenfeizhou), "3.0.0", "Apache-2.0", "https://github.com/penfeizhou/APNG4Android"),
        LibInfo(getString(R.string.add_online_storage_rclone), "1.75.0", "MIT", "https://github.com/rclone/rclone"),
        LibInfo(getString(R.string.ffmpeg_lgpl_build), "8.1.2", "LGPL-2.1", "https://ffmpeg.org"),
        LibInfo("Shizuku & Shevery API (dev.rikka.shizuku:api)", "13.1.5", "Apache-2.0", "https://github.com/HmnDev-Tech/shevery"),
    )

    // ── View builders ─────────────────────────────────────────────────────────

    private fun makeLibraryCard(lib: LibInfo): android.view.View {
        // Map SPDX identifiers to their canonical URL
        val licenseUrl = when {
            lib.url.isNotBlank() -> lib.url
            lib.license.contains("Apache-2.0", ignoreCase = true) ->
                "https://www.apache.org/licenses/LICENSE-2.0"
            lib.license.contains("LGPL-2.1", ignoreCase = true) ->
                "https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html"
            lib.license.contains("BSD-3", ignoreCase = true) ->
                "https://opensource.org/licenses/BSD-3-Clause"
            lib.license.contains("BSD-2", ignoreCase = true) ->
                "https://opensource.org/licenses/BSD-2-Clause"
            lib.license.contains("MIT", ignoreCase = true) ->
                "https://opensource.org/licenses/MIT"
            lib.license.contains("EPL-2.0", ignoreCase = true) ->
                "https://www.eclipse.org/legal/epl-2.0/"
            lib.license.contains("EPL-1.0", ignoreCase = true) ->
                "https://www.eclipse.org/legal/epl-v10.html"
            else -> ""
        }

        val card = com.google.android.material.card.MaterialCardView(this).apply {
            val margin = (8 * resources.displayMetrics.density).toInt()
            layoutParams = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT,
                LinearLayout.LayoutParams.WRAP_CONTENT
            ).also { it.bottomMargin = margin }
            radius = (12 * resources.displayMetrics.density)
            cardElevation = 0f
            val isTv2 = za.kilowatch.ultimatefilemanager.util.DeviceUtils.isTvDevice(this@LicensesActivity)
            setCardBackgroundColor(getColor(if (isTv2) R.color.tv_glass_white_10 else R.color.mobile_glass_card))
            strokeWidth = (1 * resources.displayMetrics.density).toInt()
            strokeColor = getColor(if (isTv2) R.color.tv_glass_white_20 else R.color.mobile_glass_stroke)
            if (licenseUrl.isNotBlank()) {
                isClickable = true
                isFocusable = true
                rippleColor = android.content.res.ColorStateList.valueOf(
                    getColor(if (isTv2) R.color.tv_glass_white_20 else R.color.mobile_glass_ripple)
                )
            }
        }

        val inner = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            val pad = (14 * resources.displayMetrics.density).toInt()
            setPadding(pad, pad, pad, pad)
        }

        inner.addView(makeBodyText("${lib.name}${if (lib.version.isNotBlank()) " ${lib.version}" else ""}", isBody = false))
        inner.addView(makeBodyText(lib.license, isBody = true))

        if (licenseUrl.isNotBlank()) {
            val isTv = za.kilowatch.ultimatefilemanager.util.DeviceUtils.isTvDevice(this)
            // Hint text differs: TV has no browser so we offer a copy-link fallback
            inner.addView(makeBodyText(
                if (isTv) getString(R.string.select_to_copy_link) else getString(R.string.tap_to_view_full_license),
                isBody = true
            ))

            card.setOnClickListener {
                // On TV: system stubs may resolve HTTP intents but still show the "no app"
                // toast when startActivity is called. Skip the browser attempt entirely on TV.
                if (isTv) {
                    showCopyLinkDialog(lib.name, licenseUrl)
                    return@setOnClickListener
                }

                val viewIntent = android.content.Intent(
                    android.content.Intent.ACTION_VIEW,
                    android.net.Uri.parse(licenseUrl)
                )
                @Suppress("DEPRECATION")
                val canOpen = packageManager.resolveActivity(
                    viewIntent,
                    android.content.pm.PackageManager.MATCH_DEFAULT_ONLY
                ) != null

                if (canOpen) {
                    startActivity(viewIntent)
                } else {
                    showCopyLinkDialog(lib.name, licenseUrl)
                }
            }
        }

        card.addView(inner)
        return card
    }

    /** Shows a themed dialog with the licence URL and a Copy button.
     *  Used on TV (no browser) and on any device where no browser resolves the intent. */
    private fun showCopyLinkDialog(title: String, url: String) {
        val bgColor  = try { getColor(R.color.tv_bg_gradient_end) } catch (_: Exception) { 0xFF1A1A2E.toInt() }
        val white    = try { getColor(R.color.tv_text_primary) } catch (_: Exception) { 0xFFFFFFFF.toInt() }
        val black    = try { getColor(R.color.tv_button_focused_yellow_text) } catch (_: Exception) { 0xFF000000.toInt() }
        val yellowCsl = android.content.res.ColorStateList.valueOf(
            try { getColor(R.color.tv_button_focused_yellow) } catch (_: Exception) { 0xFFFFD600.toInt() }
        )
        val glassCsl = android.content.res.ColorStateList.valueOf(0x26FFFFFF.toInt())

        val dlg = com.google.android.material.dialog.MaterialAlertDialogBuilder(
            this,
            com.google.android.material.R.style.ThemeOverlay_Material3_MaterialAlertDialog
        )
            .setTitle(title)
            .setMessage(getString(R.string.no_browser_installed_dialog_message, url))
            .setPositiveButton(getString(R.string.copy_link), null)
            .setNegativeButton(getString(R.string.close), null)
            .create()

        dlg.show()
        dlg.window?.setBackgroundDrawable(android.graphics.drawable.ColorDrawable(bgColor))
        dlg.findViewById<android.widget.TextView>(
            com.google.android.material.R.id.alertTitle
        )?.setTextColor(white)
        dlg.findViewById<android.widget.TextView>(android.R.id.message)?.setTextColor(white)
        dlg.getButton(android.app.AlertDialog.BUTTON_POSITIVE)?.apply {
            backgroundTintList = yellowCsl; setTextColor(black)
            setOnClickListener {
                val cm = getSystemService(android.content.ClipboardManager::class.java)
                cm.setPrimaryClip(android.content.ClipData.newPlainText(getString(R.string.license_url), url))
                dlg.dismiss()
            }
        }
        dlg.getButton(android.app.AlertDialog.BUTTON_NEGATIVE)?.apply {
            backgroundTintList = glassCsl; setTextColor(white)
        }
    }

    private fun makeBodyText(text: String, isBody: Boolean) = TextView(this).apply {
        this.text = text
        textSize = if (isBody) 12f else 14f
        setTextColor(getColor(when {
            isTvDevice && isBody  -> R.color.tv_text_secondary
            isTvDevice && !isBody -> R.color.tv_text_primary
            isBody                -> R.color.mobile_card_text_secondary
            else                  -> R.color.mobile_card_text_primary
        }))
        if (!isBody) typeface = android.graphics.Typeface.DEFAULT_BOLD
        layoutParams = LinearLayout.LayoutParams(
            LinearLayout.LayoutParams.MATCH_PARENT,
            LinearLayout.LayoutParams.WRAP_CONTENT
        ).also { if (isBody) it.topMargin = (2 * resources.displayMetrics.density).toInt() }
    }
}
