package za.kilowatch.ultimatefilemanager.ui.policy

import android.content.Context
import android.content.Intent
import android.content.res.ColorStateList
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.os.Bundle
import android.widget.ImageView
import android.widget.LinearLayout
import android.widget.ScrollView
import android.widget.TextView
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import com.google.android.material.card.MaterialCardView
import com.google.android.material.dialog.MaterialAlertDialogBuilder
import org.json.JSONArray
import za.kilowatch.ultimatefilemanager.R
import za.kilowatch.ultimatefilemanager.settings.FontSizeHelper
import za.kilowatch.ultimatefilemanager.settings.LocaleHelper
import za.kilowatch.ultimatefilemanager.settings.ThemeHelper
import za.kilowatch.ultimatefilemanager.util.DeviceUtils

/**
 * Open Source Licenses screen.
 *
 * Reads the licenses.json file generated by the cashapp/licensee Gradle plugin
 * (placed in res/raw/ during build) and displays each library's name, version,
 * and SPDX license identifier in a scrollable list.
 *
 * Falls back to a curated static list if the generated JSON is not yet present
 * (e.g. first-run after a clean in development).
 */
class LicensesActivity : AppCompatActivity() {

    private var isTvDevice = false

    companion object {
        fun start(context: Context) =
            context.startActivity(Intent(context, LicensesActivity::class.java))
    }

    override fun attachBaseContext(newBase: Context) {
        super.attachBaseContext(LocaleHelper.wrap(newBase))
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        ThemeHelper.applyTheme(this)
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()

        val isTv = za.kilowatch.ultimatefilemanager.util.DeviceUtils.isTvDevice(this)
        isTvDevice = isTv

        // ── Root layout ──────────────────────────────────────────────────────
        val root = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            setBackgroundResource(if (isTv) R.drawable.bg_tv_premium_dark else R.drawable.bg_mobile_gradient)
            id = R.id.main
        }

        // ── Header bar ───────────────────────────────────────────────────────
        val header = LinearLayout(this).apply {
            orientation = LinearLayout.HORIZONTAL
            gravity = android.view.Gravity.CENTER_VERTICAL
            val padH = (if (isTv) 27 else 16 * resources.displayMetrics.density).toInt()
            val padV = (14 * resources.displayMetrics.density).toInt()
            setPadding(padH, padV, padH, padV)
            setBackgroundColor(getColor(if (isTv) R.color.tv_glass_white_10 else R.color.mobile_glass_header))
            minimumHeight = ((if (isTv) 80 else 72) * resources.displayMetrics.density).toInt()
        }

        val btnBack = ImageView(this).apply {
            setImageResource(R.drawable.ic_arrow_back)
            contentDescription = getString(R.string.cd_back)
            val sizeDp = if (isTv) 52 else 44
            val size = (sizeDp * resources.displayMetrics.density).toInt()
            val p = ((if (isTv) 12 else 11) * resources.displayMetrics.density).toInt()
            setPadding(p, p, p, p)
            layoutParams = LinearLayout.LayoutParams(size, size)
            isFocusable = true
            isClickable = true
            if (isTv) {
                background = ContextCompat.getDrawable(this@LicensesActivity, R.drawable.selector_tv_icon_btn)
                imageTintList = android.content.res.ColorStateList.valueOf(getColor(R.color.tv_text_primary))
            } else {
                background = ContextCompat.getDrawable(this@LicensesActivity, R.drawable.bg_btn_icon_frosted)
                imageTintList = android.content.res.ColorStateList.valueOf(getColor(R.color.mobile_icon_tint))
            }
            setOnClickListener { finish() }
        }

        val titleText = TextView(this).apply {
            text = getString(R.string.policy_licenses_button)
            setTextColor(getColor(if (isTv) R.color.tv_text_primary else R.color.mobile_text_primary))
            textSize = if (isTv) 24f else 20f
            typeface = android.graphics.Typeface.DEFAULT_BOLD
            val margin = (16 * resources.displayMetrics.density).toInt()
            layoutParams = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.WRAP_CONTENT,
                LinearLayout.LayoutParams.WRAP_CONTENT
            ).also { it.marginStart = margin }
        }

        header.addView(btnBack)
        header.addView(titleText)

        // ── Scroll area ───────────────────────────────────────────────────────
        val scroll = ScrollView(this).apply {
            layoutParams = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT,
                LinearLayout.LayoutParams.MATCH_PARENT
            )
            clipToPadding = false
        }

        val content = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            val padH = (if (isTv) 27 else 16 * resources.displayMetrics.density).toInt()
            val padV = (16 * resources.displayMetrics.density).toInt()
            setPadding(padH, padV, padH, (padV * 3))
        }

        // ── Load license data ─────────────────────────────────────────────────
        val libraries = loadLibraries()

        if (libraries.isEmpty()) {
            content.addView(makeBodyText(
                "No license information available.\n\n" +
                getString(R.string.please_build_the_project_once_to_generate_the_license_report),
                isBody = true
            ))
        } else {
            libraries.forEach { lib ->
                content.addView(makeLibraryCard(lib))
            }
        }

        scroll.addView(content)
        root.addView(header)
        root.addView(scroll)

        setContentView(root)

        ViewCompat.setOnApplyWindowInsetsListener(root) { v, insets ->
            val bars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            v.setPadding(bars.left, bars.top, bars.right, bars.bottom)
            insets
        }
    }

    // ── Data loading ──────────────────────────────────────────────────────────

    private data class LibInfo(val name: String, val version: String, val license: String, val url: String)

    private fun loadLibraries(): List<LibInfo> {
        return try {
            val rawId = resources.getIdentifier("licenses", "raw", packageName)
            if (rawId == 0) return staticFallback()
            val json = resources.openRawResource(rawId).bufferedReader().readText()
            val arr = JSONArray(json)
            val list = (0 until arr.length()).map { i ->
                val obj = arr.getJSONObject(i)
                val name = obj.optString("name").ifBlank { obj.optString("groupId") + ":" + obj.optString("artifactId") }
                val version = obj.optString("version", "")
                val spdx = obj.optJSONArray("spdxLicenses")?.let { spdxArr ->
                    (0 until spdxArr.length()).joinToString(", ") { j ->
                        spdxArr.getJSONObject(j).optString("identifier", "")
                    }
                } ?: obj.optJSONArray("unknownLicenses")?.let { ul ->
                    (0 until ul.length()).joinToString(", ") { j ->
                        ul.getJSONObject(j).optString("name", "Unknown")
                    }
                } ?: getString(R.string.see_project_page)
                val url = obj.optString("scm", "").ifBlank {
                    obj.optJSONArray("spdxLicenses")?.optJSONObject(0)?.optString("url", "") ?: ""
                }
                LibInfo(name, version, spdx, url)
            }.toMutableList()

            if (list.none { it.name.contains("rclone", ignoreCase = true) }) {
                list.add(LibInfo(getString(R.string.add_online_storage_rclone), "1.75.0", "MIT", "https://github.com/rclone/rclone"))
            }
            if (list.none { it.name.contains("ffmpeg", ignoreCase = true) }) {
                list.add(LibInfo(getString(R.string.ffmpeg_lgpl_build), "8.1.2", "LGPL-2.1", "https://ffmpeg.org"))
            }
            if (list.none { it.name.contains("shizuku", ignoreCase = true) || it.name.contains("shevery", ignoreCase = true) }) {
                list.add(LibInfo("Shizuku & Shevery API (dev.rikka.shizuku:api)", "13.1.5", "Apache-2.0", "https://github.com/HmnDev-Tech/shevery"))
            }

            if (list.none { it.name.contains("zstd", ignoreCase = true) }) {
                list.add(LibInfo("zstd-jni (com.github.luben:zstd-jni)", "1.5.7-1", "BSD-2-Clause", "https://github.com/luben/zstd-jni"))
            }
            if (list.none { it.name.contains("junrar", ignoreCase = true) }) {
                list.add(LibInfo("Junrar (com.github.junrar:junrar)", "7.5.5", "BSD-3-Clause", "https://github.com/junrar/junrar"))
            }

            list.sortedBy { it.name.lowercase() }
        } catch (e: Exception) {
            staticFallback()
        }
    }

    private fun staticFallback() = listOf(
        LibInfo(getString(R.string.jcifsng_euagno3), "2.1.10", "LGPL-2.1", "https://github.com/AgNO3/jcifs-ng"),
        LibInfo(getString(R.string.smbj_hierynomus), "0.13.0", "Apache-2.0", "https://github.com/hierynomus/smbj"),
        LibInfo(getString(R.string.apache_commons_net), "3.10.0", "Apache-2.0", "https://commons.apache.org/proper/commons-net/"),
        LibInfo(getString(R.string.apache_commons_compress), "1.26.1", "Apache-2.0", "https://commons.apache.org/proper/commons-compress/"),
        LibInfo(getString(R.string.zip4j_netlingalazip4j), "2.11.5", "Apache-2.0", "https://github.com/svenkubiak/zip4j"),
        LibInfo(getString(R.string.xz_for_java_orgtukaanixz), "1.9", getString(R.string.public_domain), "https://tukaani.org/xz/java.html"),
        LibInfo("zstd-jni (com.github.luben:zstd-jni)", "1.5.7-1", "BSD-2-Clause", "https://github.com/luben/zstd-jni"),
        LibInfo("Junrar (com.github.junrar:junrar)", "7.5.5", "BSD-3-Clause", "https://github.com/junrar/junrar"),
        LibInfo(getString(R.string.apache_poi), "3.17", "Apache-2.0", "https://poi.apache.org/"),
        LibInfo(getString(R.string.nanohttpd), "2.3.1", "BSD-3-Clause", "https://github.com/NanoHttpd/nanohttpd"),
        LibInfo(getString(R.string.google_firebase_analytics), "", "Apache-2.0", "https://firebase.google.com/"),
        LibInfo(getString(R.string.google_billing_library), "", "Apache-2.0", "https://developer.android.com/google/play/billing"),
        LibInfo(getString(R.string.google_play_review_library), "2.0.2", "Apache-2.0", "https://developer.android.com/guide/playcore/in-app-review"),
        LibInfo(getString(R.string.androidx_libraries), "", "Apache-2.0", "https://developer.android.com/jetpack"),
        LibInfo(getString(R.string.viewpager2), "1.1.0", "Apache-2.0", "https://developer.android.com/jetpack/androidx/releases/viewpager2"),
        LibInfo(getString(R.string.libadbandroid_comgithubmuntashirakon), "3.1.1", "Apache-2.0", "https://github.com/MuntashirAkon/libadb-android"),
        LibInfo(getString(R.string.apache_sshd_core), "2.17.1", "Apache-2.0", "https://mina.apache.org/sshd-project/"),
        LibInfo(getString(R.string.eddsa_java), "0.3.0", "CC0-1.0", "https://github.com/str4d/ed25519-java"),
        LibInfo(getString(R.string.slf4j_android), "2.0.17-0", "MIT", "https://github.com/mizool/slf4j-android"),
        LibInfo(getString(R.string.bouncycastle_orgbouncycastle), "1.83", getString(R.string.bouncy_castle_license_mitstyle), "https://www.bouncycastle.org/java.html"),
        LibInfo(getString(R.string.coil_iocoilkt), "3.4.0", "Apache-2.0", "https://github.com/coil-kt/coil"),
        LibInfo(getString(R.string.apng4android_comgithubpenfeizhou), "3.0.0", "Apache-2.0", "https://github.com/penfeizhou/APNG4Android"),
        LibInfo("jxl-coder (io.github.awxkee:jxl-coder)", "2.5.2", "Apache-2.0 / BSD-3-Clause", "https://github.com/awxkee/jxl-coder-android"),
        LibInfo(getString(R.string.add_online_storage_rclone), "1.75.0", "MIT", "https://github.com/rclone/rclone"),
        LibInfo(getString(R.string.ffmpeg_lgpl_build), "8.1.2", "LGPL-2.1", "https://ffmpeg.org"),
        LibInfo("Shizuku & Shevery API (dev.rikka.shizuku:api)", "13.1.5", "Apache-2.0", "https://github.com/HmnDev-Tech/shevery"),
    )

    // ── View builders ─────────────────────────────────────────────────────────

    private fun sanitizeUrl(rawUrl: String, licenseName: String): String {
        var u = rawUrl.trim()
        if (u.startsWith("scm:git:", ignoreCase = true)) {
            u = u.substring(8).trim()
        }
        if (u.startsWith("scm:", ignoreCase = true)) {
            u = u.substring(4).trim()
        }
        if (u.startsWith("git://", ignoreCase = true)) {
            u = "https://" + u.substring(6)
        }
        if (u.startsWith("git@", ignoreCase = true)) {
            u = "https://" + u.substring(4).replace(":", "/")
        }
        if (u.endsWith(".git", ignoreCase = true)) {
            u = u.substring(0, u.length - 4)
        }
        if (!u.startsWith("http://", ignoreCase = true) && !u.startsWith("https://", ignoreCase = true)) {
            u = when {
                licenseName.contains("Apache-2.0", ignoreCase = true) -> "https://www.apache.org/licenses/LICENSE-2.0"
                licenseName.contains("LGPL-2.1", ignoreCase = true) -> "https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html"
                licenseName.contains("BSD-3", ignoreCase = true) -> "https://opensource.org/licenses/BSD-3-Clause"
                licenseName.contains("BSD-2", ignoreCase = true) -> "https://opensource.org/licenses/BSD-2-Clause"
                licenseName.contains("MIT", ignoreCase = true) -> "https://opensource.org/licenses/MIT"
                licenseName.contains("EPL-2.0", ignoreCase = true) -> "https://www.eclipse.org/legal/epl-2.0/"
                licenseName.contains("EPL-1.0", ignoreCase = true) -> "https://www.eclipse.org/legal/epl-v10.html"
                else -> ""
            }
        }
        return u
    }

    private fun makeLibraryCard(lib: LibInfo): android.view.View {
        val cleanUrl = sanitizeUrl(lib.url, lib.license)
        val isTv2 = DeviceUtils.isTvDevice(this@LicensesActivity)

        val card = MaterialCardView(this).apply {
            val margin = (8 * resources.displayMetrics.density).toInt()
            layoutParams = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT,
                LinearLayout.LayoutParams.WRAP_CONTENT
            ).also { it.bottomMargin = margin }
            radius = (16 * resources.displayMetrics.density)
            cardElevation = 0f
            setCardBackgroundColor(getColor(if (isTv2) R.color.tv_glass_white_10 else R.color.mobile_glass_card))
            strokeWidth = (1 * resources.displayMetrics.density).toInt()
            strokeColor = getColor(if (isTv2) R.color.tv_glass_white_20 else R.color.mobile_glass_stroke)
            if (cleanUrl.isNotBlank()) {
                isClickable = true
                isFocusable = true
                rippleColor = ColorStateList.valueOf(
                    getColor(if (isTv2) R.color.tv_glass_white_20 else R.color.mobile_glass_ripple)
                )
            }
            if (isTv2) {
                setOnFocusChangeListener { _, hasFocus ->
                    strokeColor = getColor(if (hasFocus) R.color.tv_button_focused_yellow else R.color.tv_glass_white_20)
                    strokeWidth = ((if (hasFocus) 2 else 1) * resources.displayMetrics.density).toInt()
                }
            }
        }

        val inner = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            val pad = (16 * resources.displayMetrics.density).toInt()
            setPadding(pad, pad, pad, pad)
        }

        // Top Row: Title + License Tag Badge
        val topRow = LinearLayout(this).apply {
            orientation = LinearLayout.HORIZONTAL
            gravity = android.view.Gravity.CENTER_VERTICAL
            layoutParams = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.MATCH_PARENT,
                LinearLayout.LayoutParams.WRAP_CONTENT
            )
        }

        val titleTv = TextView(this).apply {
            text = "${lib.name}${if (lib.version.isNotBlank()) " ${lib.version}" else ""}"
            textSize = if (isTv2) 16f else 15f
            typeface = Typeface.DEFAULT_BOLD
            setTextColor(getColor(if (isTv2) R.color.tv_text_primary else R.color.mobile_card_text_primary))
            layoutParams = LinearLayout.LayoutParams(0, LinearLayout.LayoutParams.WRAP_CONTENT, 1f)
        }

        val badge = TextView(this).apply {
            text = lib.license
            textSize = 11f
            typeface = Typeface.DEFAULT_BOLD
            setTextColor(getColor(if (isTv2) R.color.tv_accent else R.color.ufm_accent_light))
            val padH = (10 * resources.displayMetrics.density).toInt()
            val padV = (4 * resources.displayMetrics.density).toInt()
            setPadding(padH, padV, padH, padV)
            background = GradientDrawable().apply {
                shape = GradientDrawable.RECTANGLE
                cornerRadius = 8 * resources.displayMetrics.density
                setColor(getColor(if (isTv2) R.color.tv_glass_white_20 else R.color.mobile_glass_card))
                setStroke((1 * resources.displayMetrics.density).toInt(), getColor(if (isTv2) R.color.tv_glass_white_20 else R.color.mobile_glass_stroke))
            }
        }

        topRow.addView(titleTv)
        topRow.addView(badge)
        inner.addView(topRow)

        if (cleanUrl.isNotBlank()) {
            val isTv = DeviceUtils.isTvDevice(this)
            val hintTv = TextView(this).apply {
                text = if (isTv) getString(R.string.select_to_copy_link) else getString(R.string.tap_to_view_full_license)
                textSize = 12f
                setTextColor(getColor(if (isTv) R.color.tv_text_secondary else R.color.mobile_card_text_secondary))
                layoutParams = LinearLayout.LayoutParams(
                    LinearLayout.LayoutParams.MATCH_PARENT,
                    LinearLayout.LayoutParams.WRAP_CONTENT
                ).also { it.topMargin = (6 * resources.displayMetrics.density).toInt() }
            }
            inner.addView(hintTv)

            card.setOnClickListener {
                if (isTv) {
                    showModernLicenseDialog(lib.name, lib.version, lib.license, cleanUrl)
                    return@setOnClickListener
                }

                try {
                    val viewIntent = Intent(
                        Intent.ACTION_VIEW,
                        android.net.Uri.parse(cleanUrl)
                    ).apply {
                        addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                    }
                    startActivity(viewIntent)
                } catch (e: Exception) {
                    showModernLicenseDialog(lib.name, lib.version, lib.license, cleanUrl)
                }
            }
        }

        card.addView(inner)
        return card
    }

    /** Shows a modern themed glass dialog with the library details and Copy button. */
    private fun showModernLicenseDialog(name: String, version: String, license: String, url: String) {
        val isTv = DeviceUtils.isTvDevice(this)
        val density = resources.displayMetrics.density

        val dialogView = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            val pad = (20 * density).toInt()
            setPadding(pad, pad, pad, pad)
            background = ContextCompat.getDrawable(this@LicensesActivity, if (isTv) R.drawable.bg_tv_glass_card else R.drawable.bg_dialog_glass)
        }

        // Header Icon Badge + Title Container
        val headerLayout = LinearLayout(this).apply {
            orientation = LinearLayout.HORIZONTAL
            gravity = android.view.Gravity.CENTER_VERTICAL
            layoutParams = LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT)
        }

        val iconBadge = android.widget.FrameLayout(this).apply {
            val size = (44 * density).toInt()
            layoutParams = LinearLayout.LayoutParams(size, size).apply {
                marginEnd = (14 * density).toInt()
            }
            background = ContextCompat.getDrawable(this@LicensesActivity, R.drawable.bg_btn_icon_frosted)
            addView(ImageView(this@LicensesActivity).apply {
                val iconSize = (22 * density).toInt()
                layoutParams = android.widget.FrameLayout.LayoutParams(iconSize, iconSize, android.view.Gravity.CENTER)
                setImageResource(R.drawable.ic_policy)
                imageTintList = ColorStateList.valueOf(getColor(if (isTv) R.color.tv_button_focused_yellow else R.color.ufm_primary))
            })
        }

        val titleContainer = LinearLayout(this).apply {
            orientation = LinearLayout.VERTICAL
            layoutParams = LinearLayout.LayoutParams(0, LinearLayout.LayoutParams.WRAP_CONTENT, 1f)

            addView(TextView(this@LicensesActivity).apply {
                text = "$name${if (version.isNotBlank()) " $version" else ""}"
                setTextColor(getColor(if (isTv) R.color.tv_text_primary else R.color.mobile_text_primary))
                textSize = if (isTv) 18f else 16f
                typeface = Typeface.DEFAULT_BOLD
            })

            addView(TextView(this@LicensesActivity).apply {
                text = license
                setTextColor(getColor(if (isTv) R.color.tv_accent else R.color.ufm_accent_light))
                textSize = 12f
                typeface = Typeface.DEFAULT_BOLD
                setPadding(0, (2 * density).toInt(), 0, 0)
            })
        }

        headerLayout.addView(iconBadge)
        headerLayout.addView(titleContainer)
        dialogView.addView(headerLayout)

        // URL section label
        dialogView.addView(TextView(this).apply {
            text = "License & Repository URL:"
            setTextColor(getColor(if (isTv) R.color.tv_text_secondary else R.color.mobile_text_secondary))
            textSize = 12f
            setPadding(0, (16 * density).toInt(), 0, (6 * density).toInt())
        })

        // Sleek URL Box Card
        val urlCard = MaterialCardView(this).apply {
            radius = 12 * density
            cardElevation = 0f
            setCardBackgroundColor(getColor(if (isTv) R.color.tv_glass_white_10 else R.color.mobile_glass_card))
            strokeWidth = (1 * density).toInt()
            strokeColor = getColor(if (isTv) R.color.tv_glass_border else R.color.mobile_glass_stroke)
            layoutParams = LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT).apply {
                bottomMargin = (20 * density).toInt()
            }
        }

        val urlText = TextView(this).apply {
            text = url
            setTextIsSelectable(true)
            textSize = 13f
            setTextColor(getColor(if (isTv) R.color.tv_text_primary else R.color.mobile_text_primary))
            val p = (12 * density).toInt()
            setPadding(p, p, p, p)
        }
        urlCard.addView(urlText)
        dialogView.addView(urlCard)

        // Action Buttons: Copy Link + Close
        val buttonRow = LinearLayout(this).apply {
            orientation = LinearLayout.HORIZONTAL
            gravity = android.view.Gravity.END
            layoutParams = LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT)
        }

        var alertDialog: androidx.appcompat.app.AlertDialog? = null

        val btnClose = com.google.android.material.button.MaterialButton(
            this, null, android.R.attr.borderlessButtonStyle
        ).apply {
            text = getString(R.string.close)
            setTextColor(getColor(if (isTv) R.color.tv_text_secondary else R.color.mobile_text_secondary))
            textSize = 14f
            isAllCaps = false
            layoutParams = LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT, (44 * density).toInt()).apply {
                marginEnd = (8 * density).toInt()
            }
            setOnClickListener { alertDialog?.dismiss() }
        }

        val btnCopy = com.google.android.material.button.MaterialButton(this).apply {
            text = getString(R.string.copy_link)
            textSize = 14f
            isAllCaps = false
            cornerRadius = (12 * density).toInt()
            if (isTv) {
                backgroundTintList = ColorStateList.valueOf(getColor(R.color.tv_glass_white_20))
                setTextColor(getColor(R.color.tv_text_primary))
                isFocusable = true
                setOnFocusChangeListener { _, hasFocus ->
                    backgroundTintList = ColorStateList.valueOf(getColor(if (hasFocus) R.color.tv_button_focused_yellow else R.color.tv_glass_white_20))
                    setTextColor(getColor(if (hasFocus) R.color.tv_button_focused_yellow_text else R.color.tv_text_primary))
                }
            } else {
                backgroundTintList = ColorStateList.valueOf(getColor(R.color.ufm_primary))
                setTextColor(getColor(R.color.white))
            }
            layoutParams = LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT, (44 * density).toInt())
            setOnClickListener {
                val cm = getSystemService(android.content.ClipboardManager::class.java)
                cm.setPrimaryClip(android.content.ClipData.newPlainText(getString(R.string.license_url), url))
                android.widget.Toast.makeText(this@LicensesActivity, "Link copied to clipboard", android.widget.Toast.LENGTH_SHORT).show()
                alertDialog?.dismiss()
            }
        }

        buttonRow.addView(btnClose)
        buttonRow.addView(btnCopy)
        dialogView.addView(buttonRow)

        alertDialog = MaterialAlertDialogBuilder(this)
            .setView(dialogView)
            .create()

        alertDialog.show()
        alertDialog.window?.setBackgroundDrawable(android.graphics.drawable.ColorDrawable(android.graphics.Color.TRANSPARENT))
    }

    private fun makeBodyText(text: String, isBody: Boolean) = TextView(this).apply {
        this.text = text
        textSize = if (isBody) 12f else 14f
        setTextColor(getColor(when {
            isTvDevice && isBody  -> R.color.tv_text_secondary
            isTvDevice && !isBody -> R.color.tv_text_primary
            isBody                -> R.color.mobile_card_text_secondary
            else                  -> R.color.mobile_card_text_primary
        }))
        if (!isBody) typeface = Typeface.DEFAULT_BOLD
        layoutParams = LinearLayout.LayoutParams(
            LinearLayout.LayoutParams.MATCH_PARENT,
            LinearLayout.LayoutParams.WRAP_CONTENT
        ).also { if (isBody) it.topMargin = (2 * resources.displayMetrics.density).toInt() }
    }
}
